version: '3'

services:
  php-apache:
    build: ./docker/php
    restart: always
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ${PROJECT_PATH_HOST}:/var/www/html
      - ./docker/php/apache2.conf:/etc/apache2/apache2.conf
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: ${MYSQL_PORT}
      DB_DATABASE: ${MYSQL_DATABASE}
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
      LINE_ACCESS_TOKEN: ${LINE_ACCESS_TOKEN}
      LINE_CHANNEL_SECRET: ${LINE_CHANNEL_SECRET}
      HOTPEPPER_API_KEY: ${HOTPEPPER_API_KEY}
    depends_on:
      - mysql
  
  mysql:
    build: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: ${TZ}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/sql:/var/sql

volumes:
  mysql-data: